# Generated by Django 5.1.6 on 2025-02-13 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FrontendTranslation",
        ),
        migrations.DeleteModel(
            name="VersionHistory",
        ),
    ]
