# Generated by Django 5.1.4 on 2025-02-13 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Compliment",
            new_name="Letter",
        ),
        migrations.AlterModelOptions(
            name="letter",
            options={"verbose_name": "Letter", "verbose_name_plural": "Letters"},
        ),
    ]
