# Generated by Django 5.1.4 on 2025-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_rename_compliment_letter_alter_letter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="letter_command_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Letter Command Count"
            ),
        ),
    ]
